
GET http://localhost:3000/api/empleados
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwgVmVsYXNjbyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJleHAiOjE3MTU0MDUxNjcsImlzcyI6IlNlcnZpZG9yR2FtZUh1YkpXVCIsImF1ZCI6IlVzdWFyaW9zR2FtZUh1YkpXVCJ9.A73iat4Zh1XysPfytHQ6Pfqjho9wxj_6yYZhpFTjbiM

###

GET http://localhost:3000/api/roles

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "username":"patito123",
    "password":"123456"
}