
GET http://localhost:3000/api/equipos/2
Content-Type: application/application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE3MDA3MjkxLCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.AgODdq7Q-zWUNMBQBFZANNXJsuAE8QsfBYCm_vhInZg

###

GET http://localhost:3000/api/roles

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "username":"zkorpio12",
    "password":"123456"
}