
GET http://localhost:3000/api/equipos/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE3MDUyMTYwLCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.GD8_dDawnQk-tbEetxe0Ah-Vnyk6Xz7xemfJ457aAd0
###

GET http://localhost:3000/api/roles

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "username":"zkorpio12",
    "password":"123456"
}

###
GET http://localhost:3000/api/usuarios
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE3MDUzNzQ4LCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.FEqpTzpaELG4IL3teHlpy3LNenP6OWC_LykDCqBnLas

###
POST http://localhost:3000/api/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE3MDUzNzQ4LCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.FEqpTzpaELG4IL3teHlpy3LNenP6OWC_LykDCqBnLas

{
    "username":"Manuelangas",
    "password":"memelas",
    "nombre":"pues el nuevo usuario xd",
    "rol":"Recepcionista"
}
###

POST http://localhost:3000/api/equipos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE3MDQ1ODk2LCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.UCMT6zANUcmZxIGjzjUCy5bKcviQ4l3CeaCs_gJurkA

{
    "nombre":"Consola mamalona",
    "url_imagen":"https://tse1.mm.bing.net/th/id/OIP.TTX5aSRSUWJsxUNvOeUmHQHaFt?rs=1&pid=ImgDetMain",
    "modelo":"GameCube",
    "marca":"Nintendo",
    "disponibilidadId":1
}


###
PUT http://localhost:3000/api/equipos/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE3MDUwMDUzLCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.T_Dsnoc5wqlQKN8CKVdOTSoyCeSiUCT7-2-TZstbLnw

{
    "equipoId":11,
    "nombre":"La consola mamalona",
    "url_imagen":"N/A",
    "marca":"Nintendo",
    "modelo":"GameCub",
    "disponibilidadId":1
}

###
DELETE http://localhost:3000/api/equipos/11
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE3MDUyMTYwLCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.GD8_dDawnQk-tbEetxe0Ah-Vnyk6Xz7xemfJ457aAd0


--------

GET http://localhost:3000/api/equipos
Content-Type: application/application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE2NzgzNjU0LCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.74bvL9VbvR-jBd5rDfgUVywfVFFJ-4GoSXhEjAiWkuM
###

GET http://localhost:3000/api/juegos
Content-Type: application/application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE3MTQxMzIwLCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.qgvwHvxq8fegLOzg7DwmtbH7N8nIOz8PjrVPk-RedVE

GET http://localhost:3000/api/Juegos/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE2Nzg1ODUzLCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.LBxZTKF_bCwZRt3t8LmeuH9wTrx3ytX2zvmqEClBKrE


###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "username":"zkorpio12",
    "password":"123456"
}


POST http://localhost:3000/api/juegos/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemtvcnBpbzEyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiVXJpZWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzE3MTMwMjEwLCJpc3MiOiJTZXJ2aWRvckdhbWVIdWJKV1QiLCJhdWQiOiJVc3Vhcmlvc0dhbWVIdWJKV1QifQ.WWlninNM7CM9MNOEYyJd3rkt29rrFIqbhHlfgDPxycQ

{
    "nombre_juego": "Halo",
    "plataforma": "Xbox",
    "descripcion": "Un juego de disparos contra aliens asi todos feos",
    "url_imagen": "https://ejemplo.com/imagen.jpg", 
    "estatusId": 1
}

