// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backendGameHub.Data;

#nullable disable

namespace backendGameHub.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20240511064140_Creacion")]
    partial class Creacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoriaJuego", b =>
                {
                    b.Property<int>("categoriascategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("juegosjuegoId")
                        .HasColumnType("integer");

                    b.HasKey("categoriascategoriaId", "juegosjuegoId");

                    b.HasIndex("juegosjuegoId");

                    b.ToTable("CategoriaJuego");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5005675a-a217-4366-a0bf-c8e4bd1bcfb9",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "d39a8194-9da8-4451-a3e0-208b1d90dbb0",
                            Name = "Recepcionista",
                            NormalizedName = "RECEPCIONISTA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b2d84eed-f3c9-46bc-b09d-436ae2f11b96",
                            RoleId = "5005675a-a217-4366-a0bf-c8e4bd1bcfb9"
                        },
                        new
                        {
                            UserId = "1a884f5f-1b7b-4afd-8c57-4b1b1c72a2e4",
                            RoleId = "d39a8194-9da8-4451-a3e0-208b1d90dbb0"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backendGameHub.Models.Categoria", b =>
                {
                    b.Property<int>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("categoriaId"));

                    b.Property<string>("nombre_categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("categoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("backendGameHub.Models.CustomIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("protegido")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b2d84eed-f3c9-46bc-b09d-436ae2f11b96",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c80cb5ad-a4bb-48ba-a783-05aa37b9f184",
                            Email = "zkorpio12",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZKORPIO12",
                            NormalizedUserName = "ZKORPIO12",
                            PasswordHash = "AQAAAAIAAYagAAAAED5qFVeCJNsGUZOMzR4KPytUYy3Wo0dwVevcVCxow0YIRu5x3XouBUdReV16th3IwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52e7f4b1-25b1-491a-8802-0cf6487775e5",
                            TwoFactorEnabled = false,
                            UserName = "zkorpio12",
                            nombre = "Uriel",
                            protegido = true
                        },
                        new
                        {
                            Id = "1a884f5f-1b7b-4afd-8c57-4b1b1c72a2e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7c2ce96-8ad0-40d2-bea3-58d1621e8ba2",
                            Email = "patito123",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATITO123",
                            NormalizedUserName = "PATITO123",
                            PasswordHash = "AQAAAAIAAYagAAAAEBcVOkAELgJdoA1tIsv5Y1vidSobAfHlPYszD4tPNId6J0HqVmCoPQZR40SXle01/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "40a330e1-b569-4c67-89b1-175152d4a5a2",
                            TwoFactorEnabled = false,
                            UserName = "patito123",
                            nombre = "Pato Gonzalez Perez",
                            protegido = false
                        });
                });

            modelBuilder.Entity("backendGameHub.Models.Empleado", b =>
                {
                    b.Property<int>("empleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("empleadoId"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("curp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estatusId")
                        .HasColumnType("integer");

                    b.Property<string>("fecha_baja")
                        .HasColumnType("text");

                    b.Property<string>("fecha_ingreso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("personaId")
                        .HasColumnType("integer");

                    b.Property<int>("rolId")
                        .HasColumnType("integer");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("empleadoId");

                    b.HasIndex("estatusId");

                    b.HasIndex("personaId");

                    b.HasIndex("rolId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("backendGameHub.Models.Equipo", b =>
                {
                    b.Property<int>("equipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("equipoId"));

                    b.Property<int?>("estatusId")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("equipoId");

                    b.HasIndex("estatusId");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("backendGameHub.Models.Estatus", b =>
                {
                    b.Property<int>("estatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("estatusId"));

                    b.Property<string>("nombre_estatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("estatusId");

                    b.ToTable("Estatus");

                    b.HasData(
                        new
                        {
                            estatusId = 1,
                            nombre_estatus = "Activo"
                        },
                        new
                        {
                            estatusId = 2,
                            nombre_estatus = "Inactivo"
                        });
                });

            modelBuilder.Entity("backendGameHub.Models.Juego", b =>
                {
                    b.Property<int>("juegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("juegoId"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("estatusId")
                        .HasColumnType("integer");

                    b.Property<string>("nombre_juego")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("plataforma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("url_imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("juegoId");

                    b.HasIndex("estatusId");

                    b.ToTable("Juego");
                });

            modelBuilder.Entity("backendGameHub.Models.Persona", b =>
                {
                    b.Property<int>("personaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("personaId"));

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("personaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("backendGameHub.Models.Rol", b =>
                {
                    b.Property<int>("rolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rolId"));

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("rolId");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            rolId = 1,
                            nombre_rol = "Administrador"
                        },
                        new
                        {
                            rolId = 2,
                            nombre_rol = "Recepcionista"
                        });
                });

            modelBuilder.Entity("CategoriaJuego", b =>
                {
                    b.HasOne("backendGameHub.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("categoriascategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendGameHub.Models.Juego", null)
                        .WithMany()
                        .HasForeignKey("juegosjuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("backendGameHub.Models.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("backendGameHub.Models.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendGameHub.Models.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("backendGameHub.Models.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backendGameHub.Models.Empleado", b =>
                {
                    b.HasOne("backendGameHub.Models.Estatus", "estatus")
                        .WithMany("empleados")
                        .HasForeignKey("estatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendGameHub.Models.Persona", "persona")
                        .WithMany("empleados")
                        .HasForeignKey("personaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendGameHub.Models.Rol", "rol")
                        .WithMany("empleados")
                        .HasForeignKey("rolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estatus");

                    b.Navigation("persona");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("backendGameHub.Models.Equipo", b =>
                {
                    b.HasOne("backendGameHub.Models.Estatus", null)
                        .WithMany("equipos")
                        .HasForeignKey("estatusId");
                });

            modelBuilder.Entity("backendGameHub.Models.Juego", b =>
                {
                    b.HasOne("backendGameHub.Models.Estatus", null)
                        .WithMany("juegos")
                        .HasForeignKey("estatusId");
                });

            modelBuilder.Entity("backendGameHub.Models.Estatus", b =>
                {
                    b.Navigation("empleados");

                    b.Navigation("equipos");

                    b.Navigation("juegos");
                });

            modelBuilder.Entity("backendGameHub.Models.Persona", b =>
                {
                    b.Navigation("empleados");
                });

            modelBuilder.Entity("backendGameHub.Models.Rol", b =>
                {
                    b.Navigation("empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
