// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backendGameHub.Data;

#nullable disable

namespace backendGameHub.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240509225959_CreacionInicial")]
    partial class CreacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backendGameHub.Models.Empleado", b =>
                {
                    b.Property<int>("empleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("empleadoId"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("curp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estatusId")
                        .HasColumnType("integer");

                    b.Property<string>("fecha_baja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fecha_ingreso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("personaId")
                        .HasColumnType("integer");

                    b.Property<int>("rolId")
                        .HasColumnType("integer");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("empleadoId");

                    b.HasIndex("estatusId");

                    b.HasIndex("personaId");

                    b.HasIndex("rolId");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("backendGameHub.Models.Estatus", b =>
                {
                    b.Property<int>("estatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("estatusId"));

                    b.Property<string>("nombre_estatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("estatusId");

                    b.ToTable("Estatus");

                    b.HasData(
                        new
                        {
                            estatusId = 1,
                            nombre_estatus = "Activo"
                        },
                        new
                        {
                            estatusId = 2,
                            nombre_estatus = "Inactivo"
                        });
                });

            modelBuilder.Entity("backendGameHub.Models.Persona", b =>
                {
                    b.Property<int>("personaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("personaId"));

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("personaId");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("backendGameHub.Models.Rol", b =>
                {
                    b.Property<int>("rolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rolId"));

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("rolId");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            rolId = 1,
                            nombre_rol = "Administrador"
                        },
                        new
                        {
                            rolId = 2,
                            nombre_rol = "Recepcionista"
                        });
                });

            modelBuilder.Entity("backendGameHub.Models.Empleado", b =>
                {
                    b.HasOne("backendGameHub.Models.Estatus", "estatus")
                        .WithMany("empleados")
                        .HasForeignKey("estatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendGameHub.Models.Persona", "persona")
                        .WithMany("empleados")
                        .HasForeignKey("personaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendGameHub.Models.Rol", "rol")
                        .WithMany("empleados")
                        .HasForeignKey("rolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estatus");

                    b.Navigation("persona");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("backendGameHub.Models.Estatus", b =>
                {
                    b.Navigation("empleados");
                });

            modelBuilder.Entity("backendGameHub.Models.Persona", b =>
                {
                    b.Navigation("empleados");
                });

            modelBuilder.Entity("backendGameHub.Models.Rol", b =>
                {
                    b.Navigation("empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
